apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kub
  template:
    metadata:
      labels:
        app: kub
    spec:
      containers:
      - name: kub
        image: ahmadjaved/kub:latest
        ports:
        - containerPort: 3000
